version: '3.8'

services:
  jenkins:
    build: 
      context: ..
      dockerfile: jenkins/Dockerfile
    container_name: jenkins
    privileged: true
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # Remove the single Jenkinsfile mount; let Git Pipeline handle it
    networks:
      - jenkins-net

volumes:
  jenkins_home:
    name: jenkins_home

networks:
  jenkins-net:
    driver: bridge
